import { sql } from "kysely";
import { z } from "zod";
import type { Db } from "../db/index.js";
import type { TextGenerator } from "../llm/index.js";

export interface SemanticMatchDeps {
  generator: TextGenerator;
  /** Cosine similarity at/above which a pair becomes an adjudication candidate. */
  similarityThreshold?: number;
  /** Max pairs sent to the LLM per pass (cost control). */
  maxPairs?: number;
  /** Min LLM confidence to act on a "same entity" verdict. */
  minConfidence?: number;
}

export interface MergeProposal {
  survivorId: string;
  dupeId: string;
}

interface CandidateRow {
  aid: string;
  aname: string;
  aaliases: string[];
  aattrs: Record<string, unknown>;
  acreated: Date;
  bid: string;
  bname: string;
  baliases: string[];
  battrs: Record<string, unknown>;
  bcreated: Date;
  type: string;
  dist: number;
}

const DecisionSchema = z.object({
  decisions: z
    .array(
      z.object({
        i: z.number().int(),
        same: z.boolean().catch(false),
        confidence: z.number().min(0).max(1).catch(0),
      }),
    )
    .default([]),
});

function describe(name: string, aliases: string[], attrs: Record<string, unknown>): string {
  const a = aliases.length ? ` aliases=[${aliases.join(", ")}]` : "";
  const keys = ["email", "phone", "org", "title"].filter((k) => attrs[k]);
  const at = keys.length ? ` ${keys.map((k) => `${k}=${String(attrs[k])}`).join(", ")}` : "";
  return `"${name}"${a}${at}`;
}

/** Survivor = richer record: more aliases, then longer name, then older. */
function pickSurvivor(row: CandidateRow): MergeProposal {
  const aScore = row.aaliases.length;
  const bScore = row.baliases.length;
  let survivorIsA = aScore > bScore;
  if (aScore === bScore) {
    if (row.aname.length !== row.bname.length) survivorIsA = row.aname.length > row.bname.length;
    else survivorIsA = row.acreated.getTime() <= row.bcreated.getTime();
  }
  return survivorIsA
    ? { survivorId: row.aid, dupeId: row.bid }
    : { survivorId: row.bid, dupeId: row.aid };
}

/**
 * Propose entity merges semantically. Candidate pairs are generated by pgvector
 * cosine similarity over stored entity embeddings (scalable blocking), then an
 * LLM adjudicates each pair in one batched call — catching "Mike" = "Michael
 * Chen" that lexical rules miss. Returns proposals; the caller performs merges.
 * On any LLM failure it returns [] (the lexical pass result stands).
 */
export async function proposeEntityMerges(
  db: Db,
  userId: string,
  deps: SemanticMatchDeps,
): Promise<MergeProposal[]> {
  const threshold = deps.similarityThreshold ?? 0.84;
  const maxDist = 1 - threshold;
  const maxPairs = deps.maxPairs ?? 25;
  const minConfidence = deps.minConfidence ?? 0.6;

  const candidates = await sql<CandidateRow>`
    SELECT a.id AS aid, a.canonical_name AS aname, a.aliases AS aaliases, a.attrs AS aattrs, a.created_at AS acreated,
           b.id AS bid, b.canonical_name AS bname, b.aliases AS baliases, b.attrs AS battrs, b.created_at AS bcreated,
           a.type AS type, (a.embedding <=> b.embedding) AS dist
    FROM entities a
    JOIN entities b ON a.user_id = b.user_id AND a.type = b.type AND a.id < b.id
    WHERE a.user_id = ${userId}
      AND a.embedding IS NOT NULL AND b.embedding IS NOT NULL
      AND (a.embedding <=> b.embedding) <= ${maxDist}
    ORDER BY dist ASC
    LIMIT ${maxPairs}
  `.execute(db);

  if (candidates.rows.length === 0) return [];

  const lines = candidates.rows.map(
    (r, i) =>
      `${i}. type=${r.type} | A: ${describe(r.aname, r.aaliases, r.aattrs)} | B: ${describe(r.bname, r.baliases, r.battrs)}`,
  );
  const prompt = `You resolve whether two records refer to the SAME real-world entity. Nicknames, maiden names, handles, and email/phone aliases of one person/org count as the same; distinct people who merely share a first name do NOT. Return JSON {"decisions":[{"i":<index>,"same":<bool>,"confidence":<0..1>}]}.

Pairs:
${lines.join("\n")}`;

  let decisions: z.infer<typeof DecisionSchema>["decisions"];
  try {
    decisions = DecisionSchema.parse(await deps.generator.generateJson(prompt)).decisions;
  } catch {
    return [];
  }

  const proposals: MergeProposal[] = [];
  const used = new Set<string>();
  for (const d of decisions) {
    if (!d.same || d.confidence < minConfidence) continue;
    const row = candidates.rows[d.i];
    if (!row) continue;
    if (used.has(row.aid) || used.has(row.bid)) continue; // avoid merge chains in one pass
    used.add(row.aid);
    used.add(row.bid);
    proposals.push(pickSurvivor(row));
  }
  return proposals;
}
