import { sql } from "kysely";
import { z } from "zod";
import type { Db } from "../db/index.js";
import type { TextGenerator } from "../llm/index.js";

export interface SemanticNliDeps {
  generator: TextGenerator;
  similarityThreshold?: number;
  maxPairs?: number;
}

export interface ContradictionProposal {
  factId: string;
  contradictsId: string;
}

interface PairRow {
  aid: string;
  astmt: string;
  acreated: Date;
  acontra: string | null;
  bid: string;
  bstmt: string;
  bcreated: Date;
  bcontra: string | null;
  dist: number;
}

const RelationSchema = z.object({
  relations: z
    .array(
      z.object({
        i: z.number().int(),
        relation: z.enum(["contradicts", "duplicate", "unrelated"]).catch("unrelated"),
      }),
    )
    .default([]),
});

/**
 * Propose contradiction links semantically. Candidate fact pairs (same subject)
 * are generated by embedding similarity, then an LLM judges each as
 * contradicts / duplicate / unrelated — natural-language inference that catches
 * conflicts across different phrasing and predicates. Only "contradicts" is
 * acted on, and only as an advisory link (newer fact -> incumbent); duplicates
 * are left to lexical dedup. Returns `null` on LLM failure (so the caller can
 * fall back to the lexical rule); `[]` means "judged, nothing contradicts".
 */
export async function proposeContradictions(
  db: Db,
  userId: string,
  deps: SemanticNliDeps,
): Promise<ContradictionProposal[] | null> {
  const threshold = deps.similarityThreshold ?? 0.8;
  const maxDist = 1 - threshold;
  const maxPairs = deps.maxPairs ?? 25;

  const pairs = await sql<PairRow>`
    SELECT a.id AS aid, a.statement AS astmt, a.learned_at AS acreated, a.contradicts AS acontra,
           b.id AS bid, b.statement AS bstmt, b.learned_at AS bcreated, b.contradicts AS bcontra,
           (a.embedding <=> b.embedding) AS dist
    FROM facts a
    JOIN facts b ON a.user_id = b.user_id AND a.subject_id = b.subject_id AND a.id < b.id
    WHERE a.user_id = ${userId}
      AND a.status = 'active' AND b.status = 'active'
      AND a.embedding IS NOT NULL AND b.embedding IS NOT NULL
      AND (a.embedding <=> b.embedding) <= ${maxDist}
    ORDER BY dist ASC
    LIMIT ${maxPairs}
  `.execute(db);

  if (pairs.rows.length === 0) return [];

  const lines = pairs.rows.map((r, i) => `${i}. A: "${r.astmt}" | B: "${r.bstmt}"`);
  const prompt = `For each numbered pair of facts about the same subject, classify their relationship:
- "contradicts": they cannot both be true (e.g. "works at Acme" vs "works at Globex").
- "duplicate": they assert the same thing in different words.
- "unrelated": compatible / about different aspects.
Return JSON {"relations":[{"i":<index>,"relation":"contradicts|duplicate|unrelated"}]}.

Pairs:
${lines.join("\n")}`;

  let relations: z.infer<typeof RelationSchema>["relations"];
  try {
    relations = RelationSchema.parse(await deps.generator.generateJson(prompt)).relations;
  } catch {
    return null;
  }

  const proposals: ContradictionProposal[] = [];
  for (const r of relations) {
    if (r.relation !== "contradicts") continue;
    const row = pairs.rows[r.i];
    if (!row) continue;
    // Point the newer fact at the incumbent (advisory; never auto-retract).
    const [incumbent, newer] =
      row.acreated.getTime() <= row.bcreated.getTime()
        ? [row.aid, { id: row.bid, contra: row.bcontra }]
        : [row.bid, { id: row.aid, contra: row.acontra }];
    if (newer.contra) continue; // already linked
    proposals.push({ factId: newer.id, contradictsId: incumbent });
  }
  return proposals;
}
